# Generated by Django 4.1.7 on 2023-02-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cartorder_options_alter_cartorderitems_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Рейтинг товара', 'verbose_name_plural': '6. Рейтинги товаров'},
        ),
    ]
