# Generated by Django 4.1.7 on 2023-02-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Желаемое', 'verbose_name_plural': '7. Желаемое'},
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.BooleanField(default=False, verbose_name='Статус заказа'),
        ),
    ]
