# Generated by Django 4.1.7 on 2023-02-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_wishlist_options_cartorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'В процессе'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='process', max_length=150, verbose_name='Статус заказа'),
        ),
    ]
