# Generated by Django 4.1.7 on 2023-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_useraddressbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': '08.Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': '03. Заказы'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name': 'Товары заказа', 'verbose_name_plural': '04. Товары заказа'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': '01.Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': '02.Товары'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Рейтинг товара', 'verbose_name_plural': '07. Рейтинги товаров'},
        ),
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name': 'Адреса', 'verbose_name_plural': '05. Адресная книга'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Желаемое', 'verbose_name_plural': '06. Желаемое'},
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Обрабатывается', 'Обрабатывается'), ('Доставляется', 'Доставляется'), ('Выполнен', 'Выполнен')], default='Обрабатывается', max_length=150, verbose_name='Статус заказа'),
        ),
    ]
