# Generated by Django 4.1.7 on 2023-02-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_banner_options_alter_cartorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': '08. Баннеры'},
        ),
    ]
